### PR TITLE
Updated Czech lang

### PR DESCRIPTION
**Pull request by Kuldas**
I have updated the Czech translation and added the missing strings - `cookie_third_party` and `cookie_third_party_explanation`

### CODE REVIEW

**Comment by robdekort** [comment]
Nice. Thank you. Can you target the `/dev` folder instead please?

**Comment by robdekort** [comment]
Fixed it.

**Comment by Kuldas** [comment]
Hi @robdekort, 
I'm sorry, next time I'll target the `/dev` folder directly 💪

**Comment by robdekort** [comment]
Cool. No worries! Thanks again.

**Pull request merged**
