### PR TITLE
Update users.php

### PR DESCRIPTION
**Pull request by marflow**
When using the Gravatar option for the CP, the user IP is sent to an US server to see if there is a matching avatar. With GDPR in mind, it may be better to stick to the Statamic default and show the users´ initials in the icon.

Make sure you [discussed your idea](https://github.com/studio1902/statamic-peak/discussions) before doing a PR.

Fixes # .

Changes proposed in this pull request:
-

### CODE REVIEW

**Comment by robdekort** [comment]
Thinking on this a bit more I realised the CP phones home anyways. But it's not the frontend anyways. Although I'd love to stop using gravatar anyways. I think this is a good change.

**Comment by marflow** [comment]
Right. Question is what is transmitted in the call – license and version, or does it (have to) include the IP of the user? In the case of Gravatar you get a little comfort and potentially give away a a lot of data. Easy to collect where you are active but also what you said.

**Comment by robdekort** [comment]
The IP will always be included with any call anyone makes over http. But the CP phoning home stuff is required to perform the service, I doubt there would be an issue with it.

**Comment by marflow** [comment]
Guess this is what happens every time someone starts MS Word or any other licensed software for that matter. It´s technically necessary to know what CP version, add-ons and features should be available.

**Pull request merged**
