### PR TITLE
Email templates adapted from https://formspree.io

### PR DESCRIPTION
**Pull request by pryley**
The template style is adapted from https://formspree.io. They use the new {{ fields }} tag introduced in Statamic v3.0.3 to loop through the form fields.

Thoughts?

owner-html

owner-text

sender-html

sender-text

### CODE REVIEW

**Comment by robdekort** [comment]
Hey Paul thanks. Looks good! I'm gonna check this out a.s.a.p!

**Comment by robdekort** [comment]
Hey @pryley! This looks good judging from the screenshots. I haven't had the time to dive in the code. I'm wondering. Are the e-mails (and field labels) still multilingual when using that new loop function?

**Comment by robdekort** [comment]
I totally like this design better and also the simplicity of the template. The one that was in there was a thing edited over years with legacy crap in there. So this will def. be a welcome step upward!

**Comment by pryley** [comment]
> Hey @pryley! This looks good judging from the screenshots. I haven't had the time to dive in the code. I'm wondering. Are the e-mails (and field labels) still multilingual when using that new loop function?

I have not yet used the multi-site feature of Statamic, but I'll make the assumption (3d23328) that as long as the `localizable` option in the form fields is used, then the display name will be translatable.

image

**Comment by pryley** [comment]
> I totally like this design better and also the simplicity of the template. The one that was in there was a thing edited over years with legacy crap in there. So this will def. be a welcome step upward!

I have not tested the HTML across email clients, but the HTML structure is pretty identical to the emails generated by Formspree so they should be good to go.

**Comment by robdekort** [comment]
> > Hey @pryley! This looks good judging from the screenshots. I haven't had the time to dive in the code. I'm wondering. Are the e-mails (and field labels) still multilingual when using that new loop function?
> 
> I have not yet used the multi-site feature of Statamic, but I'll make the assumption ([3d23328](https://github.com/studio1902/statamic-peak/commit/3d2332806630b5dae102acf07a6e128c1ea2e783)) that as long as the `localizable` option in the form fields is used, then the display name will be translatable.
> 
> image
> 
> Also, if the assumption is correct, we could remove this from the language file:
> 
> image

Afraid not as field labels aren't translatable. So I think we can't use the loop. I'll try in dive in tomorrow.

**Comment by pryley** [comment]
> > > Hey @pryley! This looks good judging from the screenshots. I haven't had the time to dive in the code. I'm wondering. Are the e-mails (and field labels) still multilingual when using that new loop function?
> > 
> > 
> > I have not yet used the multi-site feature of Statamic, but I'll make the assumption ([3d23328](https://github.com/studio1902/statamic-peak/commit/3d2332806630b5dae102acf07a6e128c1ea2e783)) that as long as the `localizable` option in the form fields is used, then the display name will be translatable.
> > image
> > Also, if the assumption is correct, we could remove this from the language file:
> > image
> 
> Afraid not as field labels aren't translatable. So I think we can't use the loop. I'll try in dive in tomorrow.

Oh really? I'll ask on Discord, otherwise that should be submitted as an Statamic issue.

**Comment by robdekort** [comment]
I remember adding I FR for this I think. Maybe you could upvote it?

Verstuurd vanaf mijn iPhone

**Comment by pryley** [comment]
> I remember adding I FR for this I think. Maybe you could upvote it?

I can't find this. I wonder if a workaround could be to create a custom Tag that accepts the field handle as a argument and returns the translated key based on the locale... 

image

**Comment by pryley** [comment]
Something like this maybe:

```php
<?php

namespace App\Tags;

use Statamic\Facades\Site;
use Statamic\Tags\Tags;

class TransDisplay extends Tags
{
    /**
     * The {{ trans_display }} tag.
     */
    public function index()
    {
        return trans('strings.'.$this->context->get('handle'));
    }
}
```

Of course, this depends on the language file being named, `strings.php`. Perhaps a better solution is to use a dedicated `form.php` translation file for forms?

**Comment by pryley** [comment]
Got it! We can simply do this `{{ trans key="form.{ handle }" }}` and add a form.php file for form translations.

**Comment by pryley** [comment]
@robdekort I've done some testing and it seems that the generated mail templates do not use translated strings. I have created a multi-site and set the translation strings for the German language. These strings show correctly on the frontend, but are not used in the emails.

In other words, it seems that **it is unnecessary** to translate email templates; I suppose the reasoning (if it exists) is that notifications go to the admin of the site, but this does not take into account the notifications to the sender of a form.

image

image

image

**Comment by pryley** [comment]
Please see: https://github.com/statamic/cms/issues/2386

**Comment by robdekort** [comment]
So if I understand correctly. When using the new loop feature introduced in 3.0.3 we currently can't localise the fields right? If we render the fields in the mail template manually (like I did originally) we _can_ reference the php strings file and get it localised. Would be wise for now to use the manual route but merge the awesome new templates in?

**Comment by pryley** [comment]
> So if I understand correctly. When using the new loop feature introduced in 3.0.3 we currently can't localise the fields right? If we render the fields in the mail template manually (like I did originally) we _can_ reference the php strings file and get it localised. Would be wise for now to use the manual route but merge the awesome new templates in?

No, even without the loop feature it still doesn't translate any of the template text.

**Comment by robdekort** [comment]
Oh ok. That's unfortunate as this did work in v2. I guess I haven't tested this but just assumed it would work. So merge it all in now? Won't make a difference then right? There is a conflict though.

**Comment by robdekort** [comment]
I gotta be honest, I don't really like the dynamic part of rendering form fields as well. There's no way to hook in if you want to do custom stuff.

**Comment by robdekort** [comment]
Great great work. Thanks so much again Paul for working on this and explaining it to me.

**Pull request merged**
