### PR TITLE
Set correct content type of sitemap.xml

### PR DESCRIPTION
**Pull request by stefankempf**
As explained in https://stackoverflow.com/questions/3272534/what-content-type-value-should-i-send-for-my-xml-sitemap

*Always target the `/dev/` folder when proposing changes. *

Fixes # .

Changes proposed in this pull request:
-
-
-

### CODE REVIEW

**Comment by robdekort** [comment]
Thank you!

**Comment by sjclark** [comment]
Huh curious, I've always just used `xml` which Statamic by default automatically aliases to `text/xml` but from what I've just read up on `application/xml` is definitely a better choice. Wonder why it defaults to the other?

**Comment by robdekort** [comment]
I don't know either. I removed the content type - it was initially there - when Statamic added the XML template support, but Stefan found this still caused issues. At least on his server config. So it's back now :-)

**Comment by stefankempf** [comment]
> Wonder why it defaults to the other?

I tried to find out myself but didn't found any answer. As stated in the article, sitemaps.org doesn't mention the content-type at all, so it was kind of a best guess from my side.

**Pull request merged**
