### PR TITLE
Add spelling workflow

### PR DESCRIPTION
**Pull request by szepeviktor**
Add https://github.com/crate-ci/typos as a CI workflow.

Could you configure it?

### CODE REVIEW

**Comment by szepeviktor** [comment]
> Could you configure it?

Okay ... I contribute the configuration file too.

**Comment by robdekort** [comment]
Thanks, I'll have a look when I find some time. Could be I won't merge this because I don't want to overcomplicate stuff. No hard feelings pls :-).

**Comment by szepeviktor** [comment]
> I don't want to overcomplicate stuff.

This is just 1 puny workflow!!!

These 27 jobs are called "overcomplication" 😱 https://github.com/szepeviktor/byte-level-care/tree/master/.github/workflows

**Comment by robdekort** [comment]
> This is just 1 puny workflow!!!

Point is I don't know anything about workflows, what they do, how they work etc, and I'm the one maintain this thing. Also this potentially opens the door to 20 others who all just want one puny workflow added. I'll have a look soon. Thanks.

**Comment by szepeviktor** [comment]
> No hard feelings pls :-)

All right, all right.
You could go for the business.
I go for the bytes.

**Comment by robdekort** [comment]
Giving it a shot. Curious to see how it works in practice. Can always remove it annoys me too much ;-).

Thanks, appreciated.

**Pull request merged**
