### PR TITLE
add basic accordion component

### PR DESCRIPTION
**Pull request by crslp**
Changes proposed in this pull request:
- Added a basic accordion component

### CODE REVIEW

**Comment by robdekort** [comment]
I appreciate this a lot, but I feel it's too much and bespoke to be part of Peak. So I'm afraid I'm gonna have to close it.

I've been thinking about extending the `peak:add-block` command with more bespoke blocks coming from the `/stubs` folder. Whenever I add that functionality we should definitely add stuff like an accordion to it.

**Comment by websmyth** [comment]
Would love to see this as an extended `peak:add-block` as suggested. We rarely use accordions, but having the option to insert it as an optional extra would be very cool. 👀

**Comment by robdekort** [comment]
Thanks. Yeah it would be helpful to me to. Plus the community can add to it.

**Comment by robdekort** [comment]
Keep an eye out for this one: https://github.com/studio1902/statamic-peak/pull/261

Soon you can PR in more blocks. I’d love to use Alpine Components in upcoming blocks but that means you can install them without having paid for those. Hmm.

**Pull request closed without merging**
