### PR TITLE
Add Norwegian Nynorsk translation.

### PR DESCRIPTION
**Pull request by hgrimelid**
Changes proposed in this pull request:
- Added language files for Norwegian Nynorsk (nn)

### CODE REVIEW

**Comment by robdekort** [comment]
Brilliant. Thank you. Can you target the same files in the `dev/lang` folder?

**Comment by robdekort** [comment]
Thanks for the update! I can't check the files changes due to GH issues atm. So before I merge, did you also add the json file in `dev/lang/nn.json`?

**Comment by hgrimelid** [comment]
@robdekort Yep, it's there.

**Comment by robdekort** [comment]
Perfecto. Thanks!

**Pull request merged**
