### PR TITLE
Bind search submit disabled state to value's length

### PR DESCRIPTION
**Pull request by klickreflex**
Changes proposed in this pull request:
- Really prevent the search form from submitting when input is empty

### CODE REVIEW

**Comment by klickreflex** [comment]
The changes of the class order are introduced by [Headwind](https://marketplace.visualstudio.com/items?itemName=heybourn.headwind) with default config, feel free to either adapt or ignore.

**Comment by robdekort** [comment]
Cool. Thanks. Would you just commit the actual change?

**Comment by klickreflex** [comment]
> Cool. Thanks. Would you just commit the actual change?

TBH I don't know how to save without having Headwind sorting classes without disabling the addon

**Comment by robdekort** [comment]
I don't think I can edit your PR.

**Comment by klickreflex** [comment]
Okay I did disable the addon ^^

**Comment by robdekort** [comment]
Lovely sir!

**Pull request merged**
