### PR TITLE
Add some German translations

### PR DESCRIPTION
**Pull request by ymarkus**
Changes proposed in this pull request:
- I've added some German translations that were missing. Basically I just copied the English file to the German and then translated it.

### CODE REVIEW

**Comment by marcorieser** [comment]
Not sure if the `validation.php` should be in PEAK.

**Comment by robdekort** [comment]
> Not sure if the `validation.php` should be in PEAK.

Indeed. Can you take that one out @ymarkus? At some point I want to implement a language package in the install script that will take care of translation files like this. And thanks for the update!

**Comment by ymarkus** [comment]
OK, I've fixed my PR.

**Comment by robdekort** [comment]
Wunderbar!

**Pull request merged**
