### PR TITLE
Make pull quote markup more semantic

### PR DESCRIPTION
**Pull request by klickreflex**
Changes proposed in this pull request: 

- Change the pull quote's markup to a figure/blockquote/figcaption for better semantics ([further info on CSS Tricks](https://css-tricks.com/quoting-in-html-quotations-citations-and-blockquotes/#aa-hey-what-about-the-figure-element))

### CODE REVIEW

**Comment by robdekort** [comment]
Didn't know. Very nice. Thanks!

**Comment by sjclark** [comment]
I thought the interior of blockquotes was always supposed to be wrapped in `p` tags? See the spec https://www.w3.org/TR/html401/struct/text.html#edef-BLOCKQUOTE & https://www.w3.org/TR/WCAG10-HTML-TECHS/#text-quotes
🐙

**Comment by robdekort** [comment]
Hmm. It does in those examples but it doesn't say it's needed does it?

No p here btw. 
https://www.w3schools.com/TAGS/tag_blockquote.asp

**Comment by sjclark** [comment]
Thats w3**schools** - never ever trust them! 😂 

How else are you supposed to mark-up a blockquote thats more than one sentence?

**Comment by robdekort** [comment]
Well I'm happy to add a p around it but it's coming from a textarea field. So you'd never have more p's in, only br's. 

Tell me what do folks.

**Comment by sjclark** [comment]
Ahhhhhhhhhhhh, well don't worry then! Sounds like it'll just cause more trouble than good.

Ironically I spent part of yesterday wangjangling code from a dodgy API to change all the `<br>`'s to p tags :D

```
function nl2p($string)
{
    $paragraphs = '';

    foreach (explode("\n", $string) as $line) {
        if (trim($line)) {
            $paragraphs .= '<p>' . $line . '</p>';
        }
    }

    return $paragraphs;
}
```

**Comment by robdekort** [comment]
lol

**Comment by klickreflex** [comment]
I'm pretty sure you can have paragraphs inside blockquotes, but you don't have to. I'd leave it out. Then you don't end up with broken markup when you change the textarea to a bard field.

[MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blockquote) says  _permitted content_ is all [Flow content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#flow_content), which includes text nodes.

**Pull request merged**
