### PR TITLE
Tailwind v3 and v4 as a starter kit module

### PR DESCRIPTION
**Pull request by andjsch**
This PR adds Tailwind as a starter kit module, asking you which version you want to install.

Known bugs:
- [x] Despite setting ``skip_option: false`` there is still an empty choice shown and the default (v3) not selected. Fixed by new ``statamic/statamic`` version.

### CODE REVIEW

**Comment by jesseleite** [comment]
Re: `skip_option: false` not working, seems to work here 🤔

CleanShot 2024-11-27 at 13 22 41

What version of statamic/cms is installed in your app when running `php please starter-kit:install`?

**Comment by jesseleite** [comment]
It might be a good idea to add `"statamic/cms": "^5.40"` to peak's composer.json to ensure it can only be installed in latest versions, and you can bump that as you rely on new cutting edge starter kit installer features.

**Comment by andjsch** [comment]
> It might be a good idea to add `"statamic/cms": "^5.40"` to peak's composer.json to ensure it can only be installed in latest versions, and you can bump that as you rely on new cutting edge starter kit installer features.

Yep, that was it. It got fixed with the new version of ``statamic/statamic``. Thanks for taking a look!

**Comment by robdekort** [comment]
Having talked about this with Andy, we're going to await this PR https://github.com/statamic/cms/pull/11119 to solve the issue of shipping two versions of Tailwind.

Thanks both! ❤️

**Comment by andjsch** [comment]
Closing this. Tailwind v4 Beta is stable enough for production already and I personally wouldn't be surprised if we see a release before Christmas at the speed Tailwindlabs is pushing out updates…

After talking to Rob, he said he's ready to go all in on v4 already

**Pull request closed without merging**
