### PR TITLE
Sitemap Index for multisites

### PR DESCRIPTION
**Pull request by AndreasSchantl**
# Sitemap Index
Added a sitemap index that can be used in a multisite setup.

It's probably not that common, but I think it would be a nice little addition to Peak. I hope this PR will be helpful to some.

### CODE REVIEW

**Comment by robdekort** [comment]
Cool thanks. I like that it's optional. I noticed a few issues I'll fix:

1. Please target the `/dev` folder when doing PR's.
2. I removed the Antlers comments from the top of the file as they cause issues on a server together with the xml header.
3. There was a comma missing in de the routes file.
4. I had to change the sitemap.xml location line to: `<loc>{{ url | ensure_right('/') }}sitemap.xml</loc>` to support all use cases.

Thanks again!

**Comment by AndreasSchantl** [comment]
Didn't know about that issue with the comments. Is it somewhat server specific, because I have it working on all servers for me? Thanks for the info!

**Comment by robdekort** [comment]
Yeah it's weird. Maybe it was an issue in Statamic at some point but I had people asking for support because the URL wouldn't serve actual XML due to that comment. So I just removed them on those templates just to be sure.

**Comment by AndreasSchantl** [comment]
Weird. Not serving XML sounds more like the page being cached instead to me. Anyhow, thanks for the adjustments!

**Comment by robdekort** [comment]
If I remember correctly it had to do with text/content being in the file before we set the xml header which trips up some servers.

**Pull request merged**
